/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Consensus', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Consensus__factory>
getContractFactory(name: 'MeterRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MeterRegistry__factory>
getContractFactory(name: 'MeterStore', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MeterStore__factory>

  getContractAt(name: 'Consensus', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Consensus>
getContractAt(name: 'MeterRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MeterRegistry>
getContractAt(name: 'MeterStore', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MeterStore>

  deployContract(name: 'Consensus', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Consensus>
deployContract(name: 'MeterRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MeterRegistry>
deployContract(name: 'MeterStore', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MeterStore>

  deployContract(name: 'Consensus', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Consensus>
deployContract(name: 'MeterRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MeterRegistry>
deployContract(name: 'MeterStore', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MeterStore>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  